global:
  scrape_interval: 15s # Как часто собирать метрики
  evaluation_interval: 15s # Как часто оценивать правила alert'ов

scrape_configs:
  - job_name: 'phonebook-service' # Имя job'а
    metrics_path: '/actuator/prometheus' # Путь к endpoint'у Prometheus
    static_configs:
      - targets: ['host.docker.internal:8080'] # Адрес твоего Spring Boot приложения