CREATE DATABASE mydatabase;

DO
$$
BEGIN
IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = ‘myuser’) THEN
CREATE ROLE myuser WITH LOGIN PASSWORD ‘mypassword’;
ALTER ROLE myuser CREATEDB;
END IF;
END
$$;

GRANT ALL PRIVILEGES ON DATABASE mydatabase TO myuser;

CREATE TABLE IF NOT EXISTS contact (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
number VARCHAR(15) UNIQUE NOT NULL
);